### Generate a new question
POST localhost:5000/gen-question
Cookie: auth_key=IAM

# Example response
#{
#  "question_body": "How does the imagined triumph of courage sometimes amplify the fear of its actual demand?",
#  "question_explanation": "This question explores the tension between an imagined, ideal self or scenario and the daunting reality of bringing it to fruition, focusing on the fear of one's own potential for courage.",
#  "question_id": "35f2b06d-db17-462f-826a-6dc6446468b3"
#}

### Latest questions

GET localhost:5000/latest?limit=5&page=1
Cookie: auth_key=IAM

### A question

GET localhost:5000/question?question_id=5b700774-de58-49e7-a7bc-5cd74e84bda0
Cookie: auth_key=IAM

### Respond

PUT localhost:5000/response?question_id=5b700774-de58-49e7-a7bc-5cd74e84bda0&question_response=My beloved girl
Cookie: auth_key=IAM

### cine sunt

GET localhost:5000/cine-sunt
Cookie: auth_key=IAM
